name: Playwright Tests

on: [push, pull_request]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run:  npx playwright install 

    - name: Run Playwright Tests
      run: npx playwright test
